---
title: "Processing FlyTunes Exports in R"
author: "Ed Baker"
date: "`r Sys.Date()`"
output:
  html_document: 
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

The [NHMDE package](https://github.com/edwbaker/NHMDE) alongside [SonicScrewdriveR](https://sonicscrewdriver.ebaker.me.uk) can be used to pre-process the [FlyTunes](https://ebaker.me.uk/flytunes) exports from Zooniverse for analysis.

### Installation

```{r, results='hide', message=FALSE}
# If required, install the devtools package
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools")
}

# Install the NHMDE package from GitHub
devtools::install_github("edwbaker/NHMDE")

# Install the SonicScrewdriveR package from GitHub
devtools::install_github("edwbaker/SonicScrewdriveR")

# Load the packages
library(NHMDE)
library(sonicscrewdriver)
```

## Loading data

```{r}
file <- read.csv("data/flytunes-classifications.csv")

# Select workflows
file <- file[file$workflow_name != "Test 6",]
```

```{r, include=FALSE}
file <- file[1:10000,]
```


```{r}
# Process the data
data <- flytunes_process_zooniverse(file)
```

## Converting to SonicScrewdriver Annotations

```{r}
annotations <- flytunes_annotations(data)
```

## Merging sequential Annotations

```{r}
merged_annotations <- merge_annotations(annotations, same.source=FALSE)
```

```{r}
barplot(
  c(
    length(annotations),
    length(merged_annotations)
  ),
  names.arg = c("Annotations", "Merged Annotations"),
  main = "Number of Annotations before and after merging"
)
```

## References

Baker E (2021). _SonicScrewdriveR_. <https://sonicscrewdriver.ebaker.me.uk>.

Baker E (2024). _NHMDE R Package_. <https://github.com/edwbaker/NHMDE>.
